# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 使用别人封装好的的action，用于clone该仓库的源码到工作流中
    - name: Checkout
      uses: actions/checkout@v2
    # 在工作流中安装node环境（必需，这样才能在后续工作流程中运行 npm install 等指令，否则会报错）
    # - name: Setup node
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 14 # 指定node版本

    # 打包代码生成环境  
    - name: Build
      run: npm install && npm run docs:build

    - name: Deploy
      uses: cross-the-world/scp-pipeline@master
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: "124.223.33.78"
        user: root
        pass: hb3215814!
        connect_timeout: 10s
        local: './docs/.vuepress/dist/*'
        remote: /home/dist/